#!/usr/bin/env python3
"""Map Chisel-style signal queries to exact FST/GTKWave facility names."""

from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
from typing import Iterable


DEFAULT_ALIASES = {
    "allowEnq": ["io_in_ready"],
    "io.in.ready": ["io_in_ready"],
    "io.in.valid": ["io_in_valid"],
    "io.in.bits.prevInstrCount": ["io_in_bits_prevInstrCount"],
    "io.in.bits.enqEnable": ["io_in_bits_enqEnable"],
    "io.in.bits.valid": ["io_in_bits_valid"],
    "numFromFetch": ["numEnq", "io_in_bits_enqEnable"],
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Filter FST facilities and map Chisel/Scala signal names to GTKWave hierarchy names."
    )
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--fst", type=Path, help="Waveform FST file. Requires fstminer in PATH.")
    source.add_argument("--facnames", type=Path, help="Text file generated by fstminer -n.")
    parser.add_argument(
        "--scope",
        action="append",
        default=[],
        help="Scope substring filter. May be repeated. Matching uses OR across scopes.",
    )
    parser.add_argument(
        "--signals",
        default="",
        help="Comma-separated Chisel/Scala signal names to map.",
    )
    parser.add_argument(
        "--signal-file",
        type=Path,
        help="Optional file with one signal query per line. Lines after # are ignored.",
    )
    parser.add_argument(
        "--format",
        choices=("markdown", "plain"),
        default="markdown",
        help="Output format.",
    )
    parser.add_argument(
        "--cache-dir",
        type=Path,
        default=Path("/tmp"),
        help="Directory for fstminer -n cache when --fst is used.",
    )
    parser.add_argument(
        "--no-cache",
        action="store_true",
        help="Do not reuse or write fstminer cache.",
    )
    return parser.parse_args()


def normalize_facility_line(line: str) -> str | None:
    text = line.strip()
    if not text:
        return None
    top_match = re.search(r"(TOP\..*)", text)
    if top_match:
        return top_match.group(1).strip()
    if "." in text:
        return text.split()[-1]
    return None


def load_facnames(path: Path) -> list[str]:
    if not path.is_file():
        raise FileNotFoundError(f"facnames file not found: {path}")
    facilities: list[str] = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        facility = normalize_facility_line(line)
        if facility:
            facilities.append(facility)
    return facilities


def cache_path_for_fst(fst: Path, cache_dir: Path) -> Path:
    stat = fst.stat()
    key = f"{fst.resolve()}:{stat.st_size}:{int(stat.st_mtime)}"
    digest = hashlib.sha256(key.encode("utf-8")).hexdigest()[:16]
    return cache_dir / f"fst_facnames_{digest}.txt"


def facnames_from_fst(fst: Path, cache_dir: Path, no_cache: bool) -> list[str]:
    if not fst.is_file():
        raise FileNotFoundError(f"FST file not found: {fst}")
    cache = cache_path_for_fst(fst, cache_dir)
    if not no_cache and cache.is_file():
        return load_facnames(cache)
    fstminer = shutil.which("fstminer")
    if not fstminer:
        raise RuntimeError("fstminer was not found in PATH; run fstminer -n manually and pass --facnames.")
    proc = subprocess.run(
        [fstminer, "-n", str(fst)],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip() or f"fstminer failed with exit code {proc.returncode}")
    if not no_cache:
        cache_dir.mkdir(parents=True, exist_ok=True)
        cache.write_text(proc.stdout, encoding="utf-8")
    facilities = []
    for line in proc.stdout.splitlines():
        facility = normalize_facility_line(line)
        if facility:
            facilities.append(facility)
    return facilities


def strip_width(facility: str) -> str:
    return re.sub(r"\[[^\]]+\]$", "", facility)


def split_queries(signals: str, signal_file: Path | None) -> list[str]:
    queries: list[str] = []
    for item in signals.split(","):
        query = item.strip()
        if query:
            queries.append(query)
    if signal_file:
        for line in signal_file.read_text(encoding="utf-8", errors="replace").splitlines():
            query = line.split("#", 1)[0].strip()
            if query:
                queries.append(query)
    seen: set[str] = set()
    unique = []
    for query in queries:
        if query not in seen:
            unique.append(query)
            seen.add(query)
    return unique


def scope_filter(facilities: Iterable[str], scopes: list[str]) -> list[str]:
    if not scopes:
        return list(facilities)
    return [facility for facility in facilities if any(scope in facility for scope in scopes)]


def query_variants(query: str) -> list[str]:
    return [
        query,
        query.replace(".", "_").replace("(", "_").replace(")", ""),
        query.replace(".", "_"),
    ]


def choose_shortest(candidates: list[str]) -> str:
    return sorted(candidates, key=lambda item: (len(item), item))[0]


def find_one(query: str, facilities: list[str]) -> tuple[str, str, str]:
    bases = [(facility, strip_width(facility)) for facility in facilities]
    for facility, base in bases:
        if query == facility or query == base:
            return ("exact", facility, "")

    for variant in query_variants(query):
        suffix = "." + variant
        candidates = [facility for facility, base in bases if base.endswith(suffix)]
        if candidates:
            return ("exact-suffix", choose_shortest(candidates), "")

    for variant in query_variants(query):
        probe_suffix = "." + variant + "_probe"
        candidates = [facility for facility, base in bases if base.endswith(probe_suffix)]
        if candidates:
            return ("probe-suffix", choose_shortest(candidates), "matched generated probe name")

    for alias in DEFAULT_ALIASES.get(query, []):
        for alias_variant in query_variants(alias):
            suffix = "." + alias_variant
            candidates = [facility for facility, base in bases if base.endswith(suffix)]
            if candidates:
                return ("alias", choose_shortest(candidates), f"alias: {query} -> {alias}")

    tokens = [token for token in re.split(r"[^A-Za-z0-9]+", query) if token]
    if tokens:
        lowered = [token.lower() for token in tokens]
        candidates = []
        for facility, base in bases:
            name = base.lower()
            if all(token in name for token in lowered):
                candidates.append(facility)
        if candidates:
            return ("keyword", choose_shortest(candidates), "keyword match; verify before using as proof")

    return ("missing", "", "no FST facility matched")


def markdown_table(rows: list[tuple[str, str, str, str]]) -> str:
    lines = [
        "| Query | Match | GTKWave signal | Note |",
        "| --- | --- | --- | --- |",
    ]
    for query, match, signal, note in rows:
        lines.append(f"| {query} | {match} | {signal} | {note} |")
    return "\n".join(lines)


def plain_table(rows: list[tuple[str, str, str, str]]) -> str:
    lines = []
    for query, match, signal, note in rows:
        parts = [query, match, signal, note]
        lines.append("\t".join(parts).rstrip())
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    try:
        facilities = (
            facnames_from_fst(args.fst, args.cache_dir, args.no_cache)
            if args.fst
            else load_facnames(args.facnames)
        )
        scoped = scope_filter(facilities, args.scope)
        queries = split_queries(args.signals, args.signal_file)
        if not queries:
            print("No signal queries were provided. Use --signals or --signal-file.", file=sys.stderr)
            return 2
        rows = [(query, *find_one(query, scoped)) for query in queries]
        if args.format == "markdown":
            print(markdown_table(rows))
        else:
            print(plain_table(rows))
        return 0
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
